In [1]:
#Used for making HTTP requests to the URLs.
import requests

#The BeautifulSoup library is used for parsing HTML and XML documents, making it easier to extract data from them.
from bs4 import BeautifulSoup

#Used for analysing, cleaning, exploring and manipulating data.
import pandas as pd

In [3]:
#Fetching the HTML content from the website.
html_text = requests.get("https://m.cricbuzz.com/cricket-series/apps/ipl-2022/auction/teams/58#top").text

#soup object helps search and navigate through the html structure.
soup = BeautifulSoup(html_text, 'lxml')

#Capturing the entire div block.
player_cards = soup.find_all('div', class_ = "list-group-item")

#Creating an empty list named 'data'.
data = []

#For Loop to collect all the player name, their role, country, price for which they were bought and their status.
for player_card in player_cards:
    player_name = player_card.find('h3', class_ = "cb-list-heading").text
    specialist = player_card.p.get_text(strip=True).split('•')[0].strip()
    country = player_card.p.get_text(strip=True).split('•')[1].strip()
    
    price = player_card.find('div', class_ = "col-xs-4 cb-col-text-container text-center").text.replace('RETAINED', '')
    #if price is not None:
    #    price_text = price.get_text().title()
    #else:
    #    price_text = ""
    
    status = player_card.find('div', class_ = "badge bg-rtm")
    
    #As the status is in a badge format, we try to get only the text from it and replace the ones without a status to 'Released'.
    if status is not None:
        status_text = status.get_text().title()
    else:
        status_text = "Released"
    
    #Add the data to the table one after the other.
    data.append({"Players": player_name ,"Specialist": specialist ,"Country": country ,"Final Price": price, "Status": status_text})

#Creating a DataFrame 'df' and styling the table.
df = pd.DataFrame(data)
df.index = range(1, len(df) + 1)
styled_df = df.style.set_properties(**{'text-align': 'left'})
styled_df.set_table_styles([{
    'selector': 'th',
    'props': [('text-align', 'left')]
}])

styled_df